# Generated by Django 5.0.6 on 2026-06-24 00:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('emoji', models.CharField(default='🍽️', help_text='Emoji decorativo para la tarjeta de la receta.', max_length=8)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('entrada', 'Entrada'), ('fondo', 'Plato de fondo'), ('postre', 'Postre'), ('bebestible', 'Bebestible'), ('pan_masa', 'Pan y masas')], default='fondo', max_length=20)),
                ('porciones_base', models.PositiveSmallIntegerField(default=4, help_text='Número de porciones al que corresponden las cantidades guardadas.')),
                ('tiempo_preparacion_min', models.PositiveSmallIntegerField(help_text='Tiempo total estimado de preparación, en minutos.')),
                ('pasos', models.TextField(help_text='Un paso por línea. Se muestran como una lista numerada.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text="Identificador corto, ej: 'taza'.", max_length=20, unique=True)),
                ('nombre', models.CharField(help_text="Nombre legible, ej: 'taza'.", max_length=40)),
                ('abreviatura', models.CharField(help_text="Ej: 'tz', 'cda', 'g'.", max_length=10)),
                ('tipo', models.CharField(choices=[('volumen', 'Volumen (base: mililitro)'), ('masa', 'Masa (base: gramo)'), ('unidad', 'Unidad simple (no convertible)')], max_length=10)),
                ('factor_base', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Cuánto vale 1 unidad de esta medida en la unidad base de su tipo.', max_digits=10)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición en los selectores (menor a mayor).')),
            ],
            options={
                'ordering': ['tipo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nota', models.CharField(blank=True, help_text="Ej: 'a gusto', 'opcional', 'picada finamente'.", max_length=80)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='recetas.receta')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='recetas.unidad')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
